const libraries: Library[] = [
  {
    name: "NuxtLabs UI",
    logo: "nuxt.svg",
    url: "https://ui.nuxtlabs.com",
    repoOwner: "nuxtlabs",
    repoName: "ui",
    package: "@nuxthq/ui",
    filterMatchings: {
      FStyled: { match: false },
      FUnstyled: { match: false },
      FImported: { match: true },
      FPasted: { match: false },
      FTailwind: { match: true },
      FComponents: { match: true },
      FAccessible: { match: true },
      FFigma: { match: false },
      FDarkMode: {
        match: true,
        to: "https://ui.nuxtlabs.com/getting-started/theming#dark-mode",
      },
      FFree: { match: true },
      FRoadmap: { match: true, to: "https://ui.nuxtlabs.com/getting-started/roadmap" },
      FOfficial: { match: true },
    },
  },
  {
    name: "Tailwind UI",
    subName: "with Headless UI",
    logo: "tailwind.svg",
    url: "https://tailwindui.com",
    filterMatchings: {
      FStyled: { match: true },
      FUnstyled: { match: false },
      FImported: { match: false },
      FPasted: { match: true },
      FTailwind: { match: true },
      FComponents: { match: true },
      FAccessible: { match: true },
      FFigma: { match: true },
      FDarkMode: { match: false },
      FFree: { match: false },
      FRoadmap: { match: false },
      FOfficial: { match: true },
    },
  },
  {
    name: "Prime Vue",
    logo: "primevue.svg",
    url: "https://primevue.org",
    repoOwner: "primefaces",
    repoName: "primevue",
    package: "primevue",
    filterMatchings: {
      FStyled: { match: true },
      FUnstyled: { match: true },
      FImported: { match: true },
      FPasted: { match: false },
      FTailwind: { match: false },
      FComponents: { match: true },
      FAccessible: { match: false },
      FFigma: { match: false },
      FDarkMode: { match: false },
      FFree: { match: true },
      FRoadmap: { match: false },
      FOfficial: { match: false },
    },
  },
  {
    name: "Quasar",
    logo: "quasar.svg",
    logoDark: "quasar_dark.svg",
    url: "https://quasar.dev",
    repoOwner: "quasarframework",
    repoName: "quasar",
    package: "quasar",
    filterMatchings: {
      FStyled: { match: true },
      FUnstyled: { match: false },
      FImported: { match: true },
      FPasted: { match: false },
      FTailwind: { match: false },
      FComponents: { match: true },
      FAccessible: { match: false },
      FFigma: { match: true },
      FDarkMode: { match: false },
      FFree: { match: true },
      FRoadmap: { match: false },
      FOfficial: { match: false },
    },
  },
  {
    name: "Vuetify",
    logo: "vuetify.svg",
    url: "https://vuetifyjs.com",
    repoOwner: "vuetifyjs",
    repoName: "vuetify",
    package: "vuetify",
    filterMatchings: {
      FStyled: { match: true },
      FUnstyled: { match: false },
      FImported: { match: true },
      FPasted: { match: false },
      FTailwind: { match: false },
      FComponents: { match: true },
      FAccessible: { match: false },
      FFigma: { match: true },
      FDarkMode: { match: false },
      FFree: { match: true },
      FRoadmap: { match: false },
      FOfficial: { match: false },
    },
  },
  {
    name: "Daisy UI",
    repoOwner: "saadeghi",
    repoName: "daisyui",
    package: "daisyui",
    logo: "daisyui.svg",
    url: "https://daisyui.com",
    filterMatchings: {
      FStyled: { match: true },
      FUnstyled: { match: false },
      FImported: { match: true },
      FPasted: { match: false },
      FTailwind: { match: true },
      FComponents: { match: false },
      FAccessible: { match: false },
      FFigma: { match: false },
      FDarkMode: { match: false },
      FFree: { match: true },
      FRoadmap: { match: false },
      FOfficial: { match: false },
    },
  },
  {
    name: "Flowbite Vue",
    logo: "flowbite-vue.svg",
    url: "https://flowbite-vue.com",
    repoOwner: "themesberg",
    repoName: "flowbite-vue",
    package: "flowbite-vue",
    filterMatchings: {
      FStyled: { match: true },
      FUnstyled: { match: false },
      FImported: { match: true },
      FPasted: { match: false },
      FTailwind: { match: true },
      FComponents: { match: false },
      FAccessible: { match: false },
      FFigma: { match: false },
      FDarkMode: { match: false },
      FFree: { match: true },
      FRoadmap: { match: false },
      FOfficial: { match: false },
    },
  },
];

export default libraries;
