const libraries: Library[] = [
  {
    name: "NuxtLabs UI",
    logo: "nuxt.svg",
    url: "https://ui.nuxtlabs.com",
    repoUrl: "https://github.com/nuxtlabs/ui",
    nbStars: 1300,
    registryUrl: "https://www.npmjs.com/package/@nuxthq/ui",
    nbDownloads: 3305,
    filterMatchings: {
      FStyled: { match: false },
      FUnstyled: { match: false },
      FImported: { match: true },
      FPasted: { match: false },
      FTailwind: { match: true },
      FComponents: { match: true },
      FAccessible: { match: true },
      FFigma: { match: false },
      FDarkMode: {
        match: true,
        to: "https://ui.nuxtlabs.com/getting-started/theming#dark-mode",
      },
      FFree: { match: true },
      FRoadmap: { match: true, to: "https://ui.nuxtlabs.com/getting-started/roadmap" },
      FOfficial: { match: true },
    },
  },
  {
    name: "Tailwind UI",
    subName: "with Headless UI",
    logo: "tailwind.svg",
    url: "https://tailwindui.com",
    filterMatchings: {
      FStyled: { match: true },
      FUnstyled: { match: false },
      FImported: { match: false },
      FPasted: { match: true },
      FTailwind: { match: true },
      FComponents: { match: true },
      FAccessible: { match: true },
      FFigma: { match: true },
      FDarkMode: { match: false },
      FFree: { match: false },
      FRoadmap: { match: false },
      FOfficial: { match: true },
    },
  },
  {
    name: "Prime Vue",
    logo: "primevue.svg",
    url: "https://primevue.org",
    repoUrl: "https://github.com/primefaces/primevue",
    nbStars: 4045,
    registryUrl: "https://www.npmjs.com/package/primevue",
    nbDownloads: 101039,
    filterMatchings: {
      FStyled: { match: true },
      FUnstyled: { match: true },
      FImported: { match: true },
      FPasted: { match: false },
      FTailwind: { match: false },
      FComponents: { match: true },
      FAccessible: { match: false },
      FFigma: { match: false },
      FDarkMode: { match: false },
      FFree: { match: true },
      FRoadmap: { match: false },
      FOfficial: { match: false },
    },
  },
  {
    name: "Quasar",
    logo: "quasar.svg",
    logoDark: "quasar_dark.svg",
    url: "https://quasar.dev",
    repoUrl: "https://github.com/quasarframework/quasar",
    nbStars: 23900,
    registryUrl: "https://www.npmjs.com/package/quasar",
    nbDownloads: 113977,
    filterMatchings: {
      FStyled: { match: true },
      FUnstyled: { match: false },
      FImported: { match: true },
      FPasted: { match: false },
      FTailwind: { match: false },
      FComponents: { match: true },
      FAccessible: { match: false },
      FFigma: { match: true },
      FDarkMode: { match: false },
      FFree: { match: true },
      FRoadmap: { match: false },
      FOfficial: { match: false },
    },
  },
  {
    name: "Vuetify",
    logo: "vuetify.svg",
    url: "https://vuetifyjs.com",
    repoUrl: "https://github.com/vuetifyjs/vuetify",
    nbStars: 37541,
    registryUrl: "https://www.npmjs.com/package/vuetify",
    nbDownloads: 469628,
    filterMatchings: {
      FStyled: { match: true },
      FUnstyled: { match: false },
      FImported: { match: true },
      FPasted: { match: false },
      FTailwind: { match: false },
      FComponents: { match: true },
      FAccessible: { match: false },
      FFigma: { match: true },
      FDarkMode: { match: false },
      FFree: { match: true },
      FRoadmap: { match: false },
      FOfficial: { match: false },
    },
  },
  {
    name: "Daisy UI",
    repoUrl: "https://github.com/saadeghi/daisyui",
    nbStars: 23376,
    logo: "daisyui.svg",
    url: "https://daisyui.com",
    registryUrl: "https://www.npmjs.com/package/daisyui",
    nbDownloads: 160146,
    filterMatchings: {
      FStyled: { match: true },
      FUnstyled: { match: false },
      FImported: { match: true },
      FPasted: { match: false },
      FTailwind: { match: true },
      FComponents: { match: false },
      FAccessible: { match: false },
      FFigma: { match: false },
      FDarkMode: { match: false },
      FFree: { match: true },
      FRoadmap: { match: false },
      FOfficial: { match: false },
    },
  },
  {
    name: "Flowbite Vue",
    logo: "flowbite-vue.svg",
    url: "https://flowbite-vue.com",
    repoUrl: "https://github.com/themesberg/flowbite-vue",
    nbStars: 421,
    registryUrl: "https://www.npmjs.com/package/flowbite-vue",
    nbDownloads: 2952,
    filterMatchings: {
      FStyled: { match: true },
      FUnstyled: { match: false },
      FImported: { match: true },
      FPasted: { match: false },
      FTailwind: { match: true },
      FComponents: { match: false },
      FAccessible: { match: false },
      FFigma: { match: false },
      FDarkMode: { match: false },
      FFree: { match: true },
      FRoadmap: { match: false },
      FOfficial: { match: false },
    },
  },
];

export default libraries;
